/*
 * Copyright 2021 The KunStack Authors.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	publishv1beta1 "kunstack.com/pharos/pkg/apis/publish/v1beta1"
	versioned "kunstack.com/pharos/pkg/client/clientset/versioned"
	internalinterfaces "kunstack.com/pharos/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "kunstack.com/pharos/pkg/client/listers/publish/v1beta1"
)

// HelmDeployInformer provides access to a shared informer and lister for
// HelmDeploys.
type HelmDeployInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.HelmDeployLister
}

type helmDeployInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHelmDeployInformer constructs a new informer for HelmDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHelmDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHelmDeployInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHelmDeployInformer constructs a new informer for HelmDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHelmDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PublishV1beta1().HelmDeploys(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PublishV1beta1().HelmDeploys(namespace).Watch(context.TODO(), options)
			},
		},
		&publishv1beta1.HelmDeploy{},
		resyncPeriod,
		indexers,
	)
}

func (f *helmDeployInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHelmDeployInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *helmDeployInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&publishv1beta1.HelmDeploy{}, f.defaultInformer)
}

func (f *helmDeployInformer) Lister() v1beta1.HelmDeployLister {
	return v1beta1.NewHelmDeployLister(f.Informer().GetIndexer())
}
