apiVersion: v1
data:
  config.yaml: |
    log:
      level: debug
      development: true
      encoding: console
      outputPaths:
        - stdout
      errorOutputPaths:
        - stderr
    manager:
      podTemplate: |
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            app: frp-client
          name: frp-client
        spec:
          containers:
            - image: 'busybox:latest'
              imagePullPolicy: Always
              name: frp-client
              command:
                - tail
                - '-f'
              resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 128Mi
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
kind: ConfigMap
metadata:
  name: controller-manager
  namespace: system
