apiVersion: v1
data:
  config.toml: |
    [log]
    level = "debug"
    encoding = "json"
    development = true
    outputPaths = ["stdout"]
    errorOutputPaths = ["stderr"]
kind: ConfigMap
metadata:
  name: controller-manager
  namespace: system
