---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-frp-sigs-gofrp-io-v1beta1-frpserver
  failurePolicy: Fail
  name: mfrpserver.kb.io
  rules:
  - apiGroups:
    - frp.sigs.gofrp.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frpservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frp-sigs-gofrp-io-v1beta1-frpserver
  failurePolicy: Fail
  name: vfrpserver.kb.io
  rules:
  - apiGroups:
    - frp.sigs.gofrp.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frpservers
  sideEffects: None
