---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - frp.sigs.gofrp.io
  resources:
  - frpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.sigs.gofrp.io
  resources:
  - frpservers/finalizers
  verbs:
  - update
- apiGroups:
  - frp.sigs.gofrp.io
  resources:
  - frpservers/status
  verbs:
  - get
  - patch
  - update
