apiVersion: frp.gofrp.io/v1beta1
kind: FrpServer
metadata:
  labels:
    app.kubernetes.io/name: frpserver
    app.kubernetes.io/instance: frpserver-sample
    app.kubernetes.io/part-of: frp-provisioner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: frp-provisioner
  name: frpserver-sample
spec:
  auth:
    token: "test"
  serverAddr: 172.16.0.121
  externalIPs: [ "172.16.0.121" ]
  transport:
    tls:
      enable: false
