# Log log related configuration
log:
  level: debug
  development: true
  encoding: console
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]

# frp proxy configuration
frpc:
  binary_path: /bin/frpc
  workspace: /tmp/workspace
  servers:
  - server_addr: tunnel.kunstack.com
    server_port: 7000
    protocol: tcp
    tcp_mux: true
    tls_enable: false
    login_fail_exit: true
    token: 'vDUhM4TBwtV#WETijKQ3VLT$pmOS0c6hhYvnPW6Y7!Z5CXQdPB^N6wL8'
