log:
  # Log level to configure the verbosity of logging. Can be one of
  level: debug
  # Puts the logger in development mode, which changes the behavior of 'dpanic' and takes stacktraces more liberally.
  development: true
  # The encoding to use in the logging. Can be one of 'json' or 'console'
  encoding: console
  # outputPaths is a list of URLs or file paths to write logging output to.
  outputPaths: ["stdout"]
  # errorOutputPaths is a list of URLs to write internal logger errors to.
  # The default is standard error.
  #
  # Note that this setting only affects internal errors; for sample code that
  # sends error-level logs to a different location from info-level and debug-level logs.
  errorOutputPaths: ["stderr"]
manager:
  podTemplate: |
    apiVersion: v1
    kind: Pod
    metadata:
        labels:
            app: frp-client
        name: frp-client
    spec:
        containers:
            - image: busybox:latest
              imagePullPolicy: Always
              name: frp-client
              command:
                  - tail
                  - "-f"
              resources:
                  limits:
                      cpu: '1'
                      memory: 1Gi
                  requests:
                      cpu: 100m
                      memory: 128Mi
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
